2019-09-01 14:56:23,153 p=14416 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 14:56:24,721 p=14416 u=ansible |  node | CHANGED | rc=0 >>
             total       used       free     shared    buffers     cached
Mem:       4038168    3886276     151892      10688     227476    2716612
-/+ buffers/cache:     942188    3095980 
Swap:            0          0          0 

2019-09-01 14:56:25,644 p=14416 u=ansible |  node1 | CHANGED | rc=0 >>
             total       used       free     shared    buffers     cached
Mem:       4038168    3886084     152084      10996     227476    2716988
-/+ buffers/cache:     941620    3096548 
Swap:            0          0          0 

2019-09-01 14:56:26,557 p=14416 u=ansible |  db | CHANGED | rc=0 >>
             total       used       free     shared    buffers     cached
Mem:       4038168    3889168     149000      11304     227476    2717296
-/+ buffers/cache:     944396    3093772 
Swap:            0          0          0 

2019-09-01 14:56:26,721 p=14416 u=ansible |  localhost | CHANGED | rc=0 >>
              total        used        free      shared  buff/cache   available
Mem:        4038168      627160      150636       11304     3260372     3130412
Swap:             0           0           0

2019-09-01 14:59:06,751 p=15742 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 14:59:07,694 p=15742 u=ansible |  localhost | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "ping": "pong"
}
2019-09-01 14:59:07,800 p=15742 u=ansible |  db | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "ping": "pong"
}
2019-09-01 14:59:07,804 p=15742 u=ansible |  node | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "ping": "pong"
}
2019-09-01 14:59:07,859 p=15742 u=ansible |  node1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "ping": "pong"
}
2019-09-01 14:59:51,654 p=16351 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 14:59:52,865 p=16351 u=ansible |  node | CHANGED | rc=0 >>
CentOS release 6.7 (Final)

2019-09-01 14:59:53,707 p=16351 u=ansible |  node1 | CHANGED | rc=0 >>
CentOS release 6.7 (Final)

2019-09-01 14:59:54,585 p=16351 u=ansible |  db | CHANGED | rc=0 >>
CentOS release 6.7 (Final)

2019-09-01 14:59:54,745 p=16351 u=ansible |  localhost | FAILED | rc=1 >>
cat: /etc/redhat-release: No such file or directorynon-zero return code

2019-09-01 15:15:31,695 p=23563 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 15:15:31,695 p=23563 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 15:15:31,696 p=23563 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2019-09-01 15:15:31,696 p=23563 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 15:15:31,858 p=23563 u=ansible |  ERROR! the role 'php' was not found in /home/ansible/kaiser_poc/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/kaiser_poc

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 8, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      - {role: 'apache', tags: 'apache'}
      - {role: 'php', tags: 'php'}
        ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 15:43:19,654 p=3057 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 15:43:19,655 p=3057 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 15:43:19,656 p=3057 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2019-09-01 15:43:19,656 p=3057 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 15:43:19,784 p=3057 u=ansible |  ERROR! the role 'php' was not found in /home/ansible/kaiser_poc/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/kaiser_poc

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 8, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      - {role: 'apache', tags: 'apache'}
      - {role: 'php', tags: 'php'}
        ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 15:44:57,791 p=3752 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 15:44:57,791 p=3752 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 15:44:57,792 p=3752 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2019-09-01 15:44:57,792 p=3752 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 15:44:57,922 p=3752 u=ansible |  ERROR! the role 'php' was not found in /home/ansible/kaiser_poc/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/kaiser_poc

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - {role: 'apache', tags: 'apache'}
    - {role: 'php', tags: 'php'}
      ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 15:45:15,791 p=3891 u=ansible |  ansible-playbook 2.8.4
  config file = /home/ansible/kaiser_poc/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
2019-09-01 15:45:15,791 p=3891 u=ansible |  Using /home/ansible/kaiser_poc/ansible.cfg as config file
2019-09-01 15:45:20,471 p=3891 u=ansible |  host_list declined parsing /home/ansible/kaiser_poc/hosts as it did not pass it's verify_file() method
2019-09-01 15:45:20,472 p=3891 u=ansible |  Skipping due to inventory source not existing or not being readable by the current user
2019-09-01 15:45:20,472 p=3891 u=ansible |  script declined parsing /home/ansible/kaiser_poc/hosts as it did not pass it's verify_file() method
2019-09-01 15:45:20,472 p=3891 u=ansible |  auto declined parsing /home/ansible/kaiser_poc/hosts as it did not pass it's verify_file() method
2019-09-01 15:45:20,472 p=3891 u=ansible |  Skipping due to inventory source not existing or not being readable by the current user
2019-09-01 15:45:20,472 p=3891 u=ansible |  yaml declined parsing /home/ansible/kaiser_poc/hosts as it did not pass it's verify_file() method
2019-09-01 15:45:20,472 p=3891 u=ansible |  Skipping due to inventory source not existing or not being readable by the current user
2019-09-01 15:45:20,472 p=3891 u=ansible |  ini declined parsing /home/ansible/kaiser_poc/hosts as it did not pass it's verify_file() method
2019-09-01 15:45:20,472 p=3891 u=ansible |  Skipping due to inventory source not existing or not being readable by the current user
2019-09-01 15:45:20,472 p=3891 u=ansible |  toml declined parsing /home/ansible/kaiser_poc/hosts as it did not pass it's verify_file() method
2019-09-01 15:45:20,473 p=3891 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 15:45:20,473 p=3891 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 15:45:20,474 p=3891 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2019-09-01 15:45:20,475 p=3891 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 15:45:20,606 p=3891 u=ansible |  ERROR! the role 'php' was not found in /home/ansible/kaiser_poc/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/kaiser_poc

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - {role: 'apache', tags: 'apache'}
    - {role: 'php', tags: 'php'}
      ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 15:53:44,322 p=7521 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 15:53:44,322 p=7521 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 15:53:44,323 p=7521 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'

2019-09-01 15:53:44,324 p=7521 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 15:53:44,450 p=7521 u=ansible |  ERROR! the role 'php' was not found in /home/ansible/kaiser_poc/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/kaiser_poc

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 6, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - {role: 'apache', tags: 'apache'}
  - {role: 'php', tags: 'php'}
    ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 15:55:53,691 p=8409 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 15:55:53,691 p=8409 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 15:55:53,692 p=8409 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'

2019-09-01 15:55:53,693 p=8409 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 15:55:53,822 p=8409 u=ansible |  ERROR! the role 'php' was not found in /home/ansible/kaiser_poc/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/kaiser_poc

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 6, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - { role: apache, tags: [ 'apache' ] }
  - {role: 'php', tags: 'php'}
    ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 15:56:39,438 p=8688 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 15:56:39,438 p=8688 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 15:56:39,439 p=8688 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'

2019-09-01 15:56:39,439 p=8688 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 15:56:39,568 p=8688 u=ansible |  ERROR! the role 'php' was not found in /home/ansible/kaiser_poc/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/kaiser_poc

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 6, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - { role: apache, tags: [ 'apache' ] }
  - { role: 'php', tags: 'php' }
    ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 15:57:18,948 p=9085 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 15:57:18,948 p=9085 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 15:57:18,949 p=9085 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'

2019-09-01 15:57:18,949 p=9085 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 15:57:19,077 p=9085 u=ansible |  ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 5, column 41, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
  - { role: apache, tags: [ 'apache' ] };
                                        ^ here

2019-09-01 16:21:52,485 p=19735 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 16:21:52,485 p=19735 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 16:21:52,486 p=19735 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'

2019-09-01 16:21:52,486 p=19735 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 16:21:52,609 p=19735 u=ansible |  ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 5, column 43, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
  - { role: 'apache', tags: [ 'apache' ] };
                                          ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 16:24:52,275 p=21195 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 16:24:52,275 p=21195 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 16:24:52,276 p=21195 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'

2019-09-01 16:24:52,276 p=21195 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 16:24:52,405 p=21195 u=ansible |  ERROR! the role 'php' was not found in /home/ansible/kaiser_poc/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/kaiser_poc

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 6, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - { role: 'apache', tags: [ 'apache' ] }
  - { role: 'php', tags: 'php' }
    ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 16:26:50,295 p=21988 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 16:26:50,295 p=21988 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 16:26:50,296 p=21988 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'

2019-09-01 16:26:50,296 p=21988 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 16:26:50,418 p=21988 u=ansible |  ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 6, column 33, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - { role: 'apache', tags: [ 'apache' ] }
  - { role: 'php', tags: 'php' };
                                ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 16:28:58,256 p=22944 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 16:28:58,256 p=22944 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 16:28:58,257 p=22944 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'

2019-09-01 16:28:58,258 p=22944 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node1

2019-09-01 16:28:58,546 p=22944 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: app

2019-09-01 16:28:58,549 p=22944 u=ansible |  PLAY [app] **********************************************************************************************
2019-09-01 16:28:58,549 p=22944 u=ansible |  skipping: no hosts matched
2019-09-01 16:28:58,549 p=22944 u=ansible |  PLAY RECAP **********************************************************************************************
2019-09-01 16:30:27,463 p=23547 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 16:30:27,769 p=23547 u=ansible |  PLAY [app] **********************************************************************************************
2019-09-01 16:30:27,778 p=23547 u=ansible |  TASK [Gathering Facts] **********************************************************************************
2019-09-01 16:30:28,445 p=23547 u=ansible |  fatal: [node1]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "failed": true, "module_stderr": "Shared connection to node1 closed.\r\n", "module_stdout": "\r\nWe trust you have received the usual lecture from the local System\r\nAdministrator. It usually boils down to these three things:\r\n\r\n    #1) Respect the privacy of others.\r\n    #2) Think before you type.\r\n    #3) With great power comes great responsibility.\r\n\r\n\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2019-09-01 16:30:28,446 p=23547 u=ansible |  PLAY RECAP **********************************************************************************************
2019-09-01 16:30:28,446 p=23547 u=ansible |  node1                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2019-09-01 16:31:05,972 p=23897 u=ansible |  ansible-playbook 2.8.4
  config file = /home/ansible/kaiser_poc/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
2019-09-01 16:31:05,973 p=23897 u=ansible |  Using /home/ansible/kaiser_poc/ansible.cfg as config file
2019-09-01 16:31:10,259 p=23897 u=ansible |  host_list declined parsing /home/ansible/kaiser_poc/inventory.ini as it did not pass it's verify_file() method
2019-09-01 16:31:10,259 p=23897 u=ansible |  script declined parsing /home/ansible/kaiser_poc/inventory.ini as it did not pass it's verify_file() method
2019-09-01 16:31:10,259 p=23897 u=ansible |  auto declined parsing /home/ansible/kaiser_poc/inventory.ini as it did not pass it's verify_file() method
2019-09-01 16:31:10,259 p=23897 u=ansible |  yaml declined parsing /home/ansible/kaiser_poc/inventory.ini as it did not pass it's verify_file() method
2019-09-01 16:31:10,262 p=23897 u=ansible |  Parsed /home/ansible/kaiser_poc/inventory.ini inventory source with ini plugin
2019-09-01 16:31:10,263 p=23897 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 16:31:10,397 p=23897 u=ansible |  statically imported: /home/ansible/kaiser_poc/roles/apache/tasks/install.yml
2019-09-01 16:31:10,491 p=23897 u=ansible |  statically imported: /home/ansible/kaiser_poc/roles/apache/tasks/service.yml
2019-09-01 16:31:10,536 p=23897 u=ansible |  PLAYBOOK: app.yml ***************************************************************************************
2019-09-01 16:31:10,536 p=23897 u=ansible |  1 plays in app.yml
2019-09-01 16:31:10,559 p=23897 u=ansible |  PLAY [app] **********************************************************************************************
2019-09-01 16:31:10,567 p=23897 u=ansible |  TASK [Gathering Facts] **********************************************************************************
2019-09-01 16:31:10,568 p=23897 u=ansible |  task path: /home/ansible/kaiser_poc/app.yml:2
2019-09-01 16:31:10,581 p=23897 u=ansible |  <node1> ESTABLISH SSH CONNECTION FOR USER: master
2019-09-01 16:31:10,581 p=23897 u=ansible |  <node1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="master"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/a19474ea0c node1 '/bin/sh -c '"'"'echo ~master && sleep 0'"'"''
2019-09-01 16:31:10,601 p=23897 u=ansible |  <node1> (0, '/home/master\n', '')
2019-09-01 16:31:10,601 p=23897 u=ansible |  <node1> ESTABLISH SSH CONNECTION FOR USER: master
2019-09-01 16:31:10,602 p=23897 u=ansible |  <node1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="master"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/a19474ea0c node1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/master/.ansible/tmp/ansible-tmp-1567355470.58-216587790724252 `" && echo ansible-tmp-1567355470.58-216587790724252="` echo /home/master/.ansible/tmp/ansible-tmp-1567355470.58-216587790724252 `" ) && sleep 0'"'"''
2019-09-01 16:31:10,622 p=23897 u=ansible |  <node1> (0, 'ansible-tmp-1567355470.58-216587790724252=/home/master/.ansible/tmp/ansible-tmp-1567355470.58-216587790724252\n', '')
2019-09-01 16:31:10,910 p=23897 u=ansible |  <node1> Attempting python interpreter discovery
2019-09-01 16:31:10,910 p=23897 u=ansible |  <node1> ESTABLISH SSH CONNECTION FOR USER: master
2019-09-01 16:31:10,911 p=23897 u=ansible |  <node1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="master"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/a19474ea0c node1 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
2019-09-01 16:31:10,931 p=23897 u=ansible |  <node1> (0, 'PLATFORM\nLinux\nFOUND\n/usr/bin/python\n/usr/bin/python2.6\n/usr/bin/python\nENDFOUND\n', '')
2019-09-01 16:31:10,931 p=23897 u=ansible |  <node1> ESTABLISH SSH CONNECTION FOR USER: master
2019-09-01 16:31:10,932 p=23897 u=ansible |  <node1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="master"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/a19474ea0c node1 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
2019-09-01 16:31:10,973 p=23897 u=ansible |  <node1> (0, '{"osrelease_content": null, "platform_dist_result": ["centos", "6.7", "Final"]}\n', '')
2019-09-01 16:31:10,977 p=23897 u=ansible |  Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/setup.py
2019-09-01 16:31:10,979 p=23897 u=ansible |  <node1> PUT /home/ansible/.ansible/tmp/ansible-local-23897bG_mAD/tmpfQZPmf TO /home/master/.ansible/tmp/ansible-tmp-1567355470.58-216587790724252/AnsiballZ_setup.py
2019-09-01 16:31:10,979 p=23897 u=ansible |  <node1> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="master"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/a19474ea0c '[node1]'
2019-09-01 16:31:11,016 p=23897 u=ansible |  <node1> (0, 'sftp> put /home/ansible/.ansible/tmp/ansible-local-23897bG_mAD/tmpfQZPmf /home/master/.ansible/tmp/ansible-tmp-1567355470.58-216587790724252/AnsiballZ_setup.py\n', '')
2019-09-01 16:31:11,017 p=23897 u=ansible |  <node1> ESTABLISH SSH CONNECTION FOR USER: master
2019-09-01 16:31:11,017 p=23897 u=ansible |  <node1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="master"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/a19474ea0c node1 '/bin/sh -c '"'"'chmod u+x /home/master/.ansible/tmp/ansible-tmp-1567355470.58-216587790724252/ /home/master/.ansible/tmp/ansible-tmp-1567355470.58-216587790724252/AnsiballZ_setup.py && sleep 0'"'"''
2019-09-01 16:31:11,037 p=23897 u=ansible |  <node1> (0, '', '')
2019-09-01 16:31:11,037 p=23897 u=ansible |  <node1> ESTABLISH SSH CONNECTION FOR USER: master
2019-09-01 16:31:11,038 p=23897 u=ansible |  <node1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="master"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/a19474ea0c -tt node1 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=edmxhqzbobdefncuayuxpmqtqjbxwksj] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-edmxhqzbobdefncuayuxpmqtqjbxwksj ; /usr/bin/python /home/master/.ansible/tmp/ansible-tmp-1567355470.58-216587790724252/AnsiballZ_setup.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
2019-09-01 16:31:11,079 p=23897 u=ansible |  Escalation succeeded
2019-09-01 16:31:11,080 p=23897 u=ansible |  <node1> (1, '\r\n', 'Shared connection to node1 closed.\r\n')
2019-09-01 16:31:11,080 p=23897 u=ansible |  <node1> Failed to connect to the host via ssh: Shared connection to node1 closed.
2019-09-01 16:31:11,082 p=23897 u=ansible |  <node1> ESTABLISH SSH CONNECTION FOR USER: master
2019-09-01 16:31:11,083 p=23897 u=ansible |  <node1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="master"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/a19474ea0c node1 '/bin/sh -c '"'"'rm -f -r /home/master/.ansible/tmp/ansible-tmp-1567355470.58-216587790724252/ > /dev/null 2>&1 && sleep 0'"'"''
2019-09-01 16:31:11,102 p=23897 u=ansible |  <node1> (0, '', '')
2019-09-01 16:31:11,108 p=23897 u=ansible |  fatal: [node1]: FAILED! => {
    "ansible_facts": {}, 
    "changed": false, 
    "failed_modules": {
        "setup": {
            "ansible_facts": {
                "discovered_interpreter_python": "/usr/bin/python"
            }, 
            "failed": true, 
            "module_stderr": "Shared connection to node1 closed.\r\n", 
            "module_stdout": "\r\n", 
            "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
            "rc": 1
        }
    }, 
    "msg": "The following modules failed to execute: setup\n"
}
2019-09-01 16:31:11,109 p=23897 u=ansible |  PLAY RECAP **********************************************************************************************
2019-09-01 16:31:11,109 p=23897 u=ansible |  node1                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2019-09-01 16:33:45,181 p=25029 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 16:33:45,487 p=25029 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 16:33:45,496 p=25029 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 16:33:46,118 p=25029 u=ansible |  fatal: [node1]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "failed": true, "module_stderr": "Shared connection to node1 closed.\r\n", "module_stdout": "\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2019-09-01 16:33:46,123 p=25029 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 16:33:46,123 p=25029 u=ansible |  node1                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2019-09-01 16:51:41,339 p=681 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 16:51:41,639 p=681 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 16:51:41,648 p=681 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 16:51:42,336 p=681 u=ansible |  fatal: [node1]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "failed": true, "module_stderr": "Shared connection to node1 closed.\r\n", "module_stdout": "\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2019-09-01 16:51:42,337 p=681 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 16:51:42,338 p=681 u=ansible |  node1                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2019-09-01 16:52:59,722 p=1369 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 16:53:00,971 p=1369 u=ansible |  node1 | CHANGED | rc=0 >>
CentOS release 6.7 (Final)

2019-09-01 16:53:52,570 p=1810 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 16:53:52,862 p=1810 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 16:53:52,870 p=1810 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 16:53:53,451 p=1810 u=ansible |  fatal: [node1]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "failed": true, "module_stderr": "Shared connection to node1 closed.\r\n", "module_stdout": "\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2019-09-01 16:53:53,453 p=1810 u=ansible |  fatal: [node]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "failed": true, "module_stderr": "Shared connection to node closed.\r\n", "module_stdout": "\r\nWe trust you have received the usual lecture from the local System\r\nAdministrator. It usually boils down to these three things:\r\n\r\n    #1) Respect the privacy of others.\r\n    #2) Think before you type.\r\n    #3) With great power comes great responsibility.\r\n\r\n\r\n\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2019-09-01 16:53:53,454 p=1810 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 16:53:53,455 p=1810 u=ansible |  node                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2019-09-01 16:53:53,455 p=1810 u=ansible |  node1                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2019-09-01 17:00:48,685 p=5015 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 17:00:48,982 p=5015 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 17:00:48,990 p=5015 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 17:00:49,577 p=5015 u=ansible |  fatal: [node1]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "failed": true, "module_stderr": "Shared connection to node1 closed.\r\n", "module_stdout": "\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2019-09-01 17:00:49,578 p=5015 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 17:00:49,578 p=5015 u=ansible |  node1                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2019-09-01 17:25:36,504 p=15893 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 17:25:36,798 p=15893 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 17:25:36,807 p=15893 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 17:25:50,196 p=15893 u=ansible |  ok: [node1]
2019-09-01 17:25:50,218 p=15893 u=ansible |  TASK [apache : install the apache web server] *******************************************************************************************************
2019-09-01 17:26:16,631 p=15893 u=ansible |  changed: [node1]
2019-09-01 17:26:16,653 p=15893 u=ansible |  TASK [apache : start apche web server] **************************************************************************************************************
2019-09-01 17:26:18,790 p=15893 u=ansible |  changed: [node1]
2019-09-01 17:26:18,792 p=15893 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 17:26:18,792 p=15893 u=ansible |  node1                      : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2019-09-01 17:36:22,506 p=21186 u=ansible |   [WARNING]: Unable to parse /home/ansible/kaiser_poc/hosts as an inventory source

2019-09-01 17:36:22,506 p=21186 u=ansible |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-09-01 17:36:22,507 p=21186 u=ansible |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2019-09-01 17:36:22,508 p=21186 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: node

2019-09-01 17:36:22,798 p=21186 u=ansible |   [WARNING]: Could not match supplied host pattern, ignoring: app

2019-09-01 17:36:22,801 p=21186 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 17:36:22,801 p=21186 u=ansible |  skipping: no hosts matched
2019-09-01 17:36:22,801 p=21186 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 17:36:42,400 p=21327 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 17:36:42,702 p=21327 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 17:36:42,711 p=21327 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 17:36:43,314 p=21327 u=ansible |  fatal: [node]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "failed": true, "module_stderr": "Shared connection to node closed.\r\n", "module_stdout": "\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2019-09-01 17:36:43,315 p=21327 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 17:36:43,315 p=21327 u=ansible |  node                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2019-09-01 17:39:47,616 p=22731 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 17:39:47,908 p=22731 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 17:39:47,916 p=22731 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 17:40:00,853 p=22731 u=ansible |  ok: [node]
2019-09-01 17:40:00,875 p=22731 u=ansible |  TASK [apache : install the apache web server] *******************************************************************************************************
2019-09-01 17:40:26,492 p=22731 u=ansible |  changed: [node]
2019-09-01 17:40:26,514 p=22731 u=ansible |  TASK [apache : start apche web server] **************************************************************************************************************
2019-09-01 17:40:28,680 p=22731 u=ansible |  changed: [node]
2019-09-01 17:40:28,683 p=22731 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 17:40:28,683 p=22731 u=ansible |  node                       : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2019-09-01 18:07:52,610 p=3058 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 18:07:52,748 p=3058 u=ansible |  ERROR! Syntax Error while loading YAML.
  found unacceptable key (unhashable type: 'AnsibleMapping')

The error appears to be in '/home/ansible/kaiser_poc/roles/apache/tasks/install.yml': line 4, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

     yum:
       name: {{ package_name }}
              ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2019-09-01 18:12:05,351 p=4890 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 18:12:05,648 p=4890 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 18:12:05,658 p=4890 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 18:12:18,573 p=4890 u=ansible |  ok: [node]
2019-09-01 18:12:18,595 p=4890 u=ansible |  TASK [apache : install the apache web server] *******************************************************************************************************
2019-09-01 18:12:23,147 p=4890 u=ansible |  ok: [node]
2019-09-01 18:12:23,169 p=4890 u=ansible |  TASK [apache : install apache2 web server] **********************************************************************************************************
2019-09-01 18:12:23,197 p=4890 u=ansible |  skipping: [node]
2019-09-01 18:12:23,220 p=4890 u=ansible |  TASK [apache : start apache web server] *************************************************************************************************************
2019-09-01 18:12:24,774 p=4890 u=ansible |  ok: [node]
2019-09-01 18:12:24,796 p=4890 u=ansible |  TASK [apache : start apache2 web server] ************************************************************************************************************
2019-09-01 18:12:25,082 p=4890 u=ansible |  fatal: [node]: FAILED! => {"changed": false, "msg": "Could not find the requested service apache2: host"}
2019-09-01 18:12:25,084 p=4890 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 18:12:25,084 p=4890 u=ansible |  node                       : ok=3    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2019-09-01 19:36:23,028 p=9298 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 19:36:23,322 p=9298 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 19:36:23,332 p=9298 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 19:36:36,290 p=9298 u=ansible |  ok: [node]
2019-09-01 19:36:36,312 p=9298 u=ansible |  TASK [apache : install the apache web server] *******************************************************************************************************
2019-09-01 19:36:40,638 p=9298 u=ansible |  ok: [node]
2019-09-01 19:36:40,659 p=9298 u=ansible |  TASK [apache : install apache2 web server] **********************************************************************************************************
2019-09-01 19:36:40,678 p=9298 u=ansible |  skipping: [node]
2019-09-01 19:36:40,701 p=9298 u=ansible |  TASK [apache : start apache web server] *************************************************************************************************************
2019-09-01 19:36:42,290 p=9298 u=ansible |  ok: [node]
2019-09-01 19:36:42,311 p=9298 u=ansible |  TASK [apache : start apache2 web server] ************************************************************************************************************
2019-09-01 19:36:42,591 p=9298 u=ansible |  fatal: [node]: FAILED! => {"changed": false, "msg": "Could not find the requested service apache2: host"}
2019-09-01 19:36:42,592 p=9298 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 19:36:42,592 p=9298 u=ansible |  node                       : ok=3    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2019-09-01 19:40:03,984 p=11318 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 19:40:04,284 p=11318 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 19:40:04,294 p=11318 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 19:40:17,262 p=11318 u=ansible |  ok: [node]
2019-09-01 19:40:17,285 p=11318 u=ansible |  TASK [apache : install the apache web server] *******************************************************************************************************
2019-09-01 19:40:22,104 p=11318 u=ansible |  ok: [node]
2019-09-01 19:40:22,128 p=11318 u=ansible |  TASK [apache : install apache2 web server] **********************************************************************************************************
2019-09-01 19:40:22,145 p=11318 u=ansible |  skipping: [node]
2019-09-01 19:40:22,167 p=11318 u=ansible |  TASK [apache : start apache web server] *************************************************************************************************************
2019-09-01 19:40:23,712 p=11318 u=ansible |  ok: [node]
2019-09-01 19:40:23,734 p=11318 u=ansible |  TASK [apache : start apache2 web server] ************************************************************************************************************
2019-09-01 19:40:24,025 p=11318 u=ansible |  fatal: [node]: FAILED! => {"changed": false, "msg": "Could not find the requested service apache2: host"}
2019-09-01 19:40:24,026 p=11318 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 19:40:24,026 p=11318 u=ansible |  node                       : ok=3    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2019-09-01 19:40:55,209 p=12040 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 19:40:55,508 p=12040 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 19:40:55,518 p=12040 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 19:41:08,416 p=12040 u=ansible |  ok: [node]
2019-09-01 19:41:08,439 p=12040 u=ansible |  TASK [apache : install the apache web server] *******************************************************************************************************
2019-09-01 19:41:12,708 p=12040 u=ansible |  ok: [node]
2019-09-01 19:41:12,730 p=12040 u=ansible |  TASK [apache : install apache2 web server] **********************************************************************************************************
2019-09-01 19:41:12,746 p=12040 u=ansible |  skipping: [node]
2019-09-01 19:41:12,767 p=12040 u=ansible |  TASK [apache : start apache web server] *************************************************************************************************************
2019-09-01 19:41:14,333 p=12040 u=ansible |  ok: [node]
2019-09-01 19:41:14,355 p=12040 u=ansible |  TASK [apache : start apache2 web server] ************************************************************************************************************
2019-09-01 19:41:14,637 p=12040 u=ansible |  fatal: [node]: FAILED! => {"changed": false, "msg": "Could not find the requested service apache2: host"}
2019-09-01 19:41:14,639 p=12040 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 19:41:14,639 p=12040 u=ansible |  node                       : ok=3    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2019-09-01 19:42:51,659 p=13299 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 19:42:51,957 p=13299 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 19:42:51,967 p=13299 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 19:43:04,899 p=13299 u=ansible |  ok: [node]
2019-09-01 19:43:04,924 p=13299 u=ansible |  TASK [apache : describe the hosts] ******************************************************************************************************************
2019-09-01 19:43:04,942 p=13299 u=ansible |  ok: [node] => {
    "msg": "Computer node is running RedHat or equivalent"
}
2019-09-01 19:43:04,964 p=13299 u=ansible |  TASK [apache : install the apache web server] *******************************************************************************************************
2019-09-01 19:43:09,554 p=13299 u=ansible |  ok: [node]
2019-09-01 19:43:09,577 p=13299 u=ansible |  TASK [apache : install apache2 web server] **********************************************************************************************************
2019-09-01 19:43:09,594 p=13299 u=ansible |  skipping: [node]
2019-09-01 19:43:09,616 p=13299 u=ansible |  TASK [apache : start apache web server] *************************************************************************************************************
2019-09-01 19:43:11,182 p=13299 u=ansible |  ok: [node]
2019-09-01 19:43:11,204 p=13299 u=ansible |  TASK [apache : start apache2 web server] ************************************************************************************************************
2019-09-01 19:43:11,490 p=13299 u=ansible |  fatal: [node]: FAILED! => {"changed": false, "msg": "Could not find the requested service apache2: host"}
2019-09-01 19:43:11,491 p=13299 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 19:43:11,491 p=13299 u=ansible |  node                       : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
2019-09-01 19:55:23,142 p=19264 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 19:55:23,269 p=19264 u=ansible |  ERROR! Syntax Error while loading YAML.
  did not find expected '-' indicator

The error appears to be in '/home/ansible/kaiser_poc/app.yml': line 7, column 35, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - { role: 'apache', tags: [ 'apache' ] }
    - { role: 'php', tags: 'php' };
                                  ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

2019-09-01 19:55:42,533 p=19407 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 19:55:42,850 p=19407 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 19:55:42,861 p=19407 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 19:55:55,801 p=19407 u=ansible |  ok: [node]
2019-09-01 19:55:55,825 p=19407 u=ansible |  TASK [php : install php] ****************************************************************************************************************************
2019-09-01 19:55:59,538 p=19407 u=ansible |  changed: [node] => (item=php)
2019-09-01 19:56:02,971 p=19407 u=ansible |  changed: [node] => (item=php-mysql)
2019-09-01 19:56:02,979 p=19407 u=ansible |  RUNNING HANDLER [php : restart apache] **************************************************************************************************************
2019-09-01 19:56:14,313 p=19407 u=ansible |  changed: [node]
2019-09-01 19:56:14,315 p=19407 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 19:56:14,315 p=19407 u=ansible |  node                       : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2019-09-01 20:15:20,247 p=28317 u=ansible |   [WARNING]: Found both group and host with same name: db

2019-09-01 20:15:20,557 p=28317 u=ansible |  PLAY [app] ******************************************************************************************************************************************
2019-09-01 20:15:20,569 p=28317 u=ansible |  TASK [Gathering Facts] ******************************************************************************************************************************
2019-09-01 20:15:33,508 p=28317 u=ansible |  ok: [node]
2019-09-01 20:15:33,530 p=28317 u=ansible |  TASK [php : install php] ****************************************************************************************************************************
2019-09-01 20:15:34,182 p=28317 u=ansible |  ok: [node] => (item=php)
2019-09-01 20:15:34,610 p=28317 u=ansible |  ok: [node] => (item=php-mysql)
2019-09-01 20:15:34,632 p=28317 u=ansible |  TASK [php : create release directory  structure] ****************************************************************************************************
2019-09-01 20:15:35,075 p=28317 u=ansible |  changed: [node]
2019-09-01 20:15:35,098 p=28317 u=ansible |  TASK [php : install the index file] *****************************************************************************************************************
2019-09-01 20:15:36,940 p=28317 u=ansible |  changed: [node]
2019-09-01 20:15:36,965 p=28317 u=ansible |  TASK [php : setup symlinks] *************************************************************************************************************************
2019-09-01 20:15:37,227 p=28317 u=ansible |  changed: [node]
2019-09-01 20:15:37,229 p=28317 u=ansible |  PLAY RECAP ******************************************************************************************************************************************
2019-09-01 20:15:37,229 p=28317 u=ansible |  node                       : ok=5    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
